"""
Phase 5D — Counterfactual Intervention Analysis

THE UNIQUE CONTRIBUTION OF THIS PAPER
--------------------------------------
No prior wildfire burn probability paper applies counterfactual GNN
intervention analysis. This script answers the management question:

  "What happens to burn probability if we intervene on the landscape?"

Three scenarios, all with calibrated uncertainty bounds:
  1. Fuel reduction 30%    — reduce CFL by 30% across all test nodes
  2. Firebreak strip       — set CFL=0 in a horizontal landscape band
  3. Ignition suppression  — reduce Ignition_Prob by 50% across test nodes

The GNN propagates intervention effects through spatial topology —
adjacent cells see changed neighborhood features → their predictions
also change. This is impossible in XGBoost (no topology) or CNN (fixed kernel).

USAGE
-----
    conda activate wildfire-gnn
    cd spatiotemporal_wildfire_gnn

    # Run all 3 scenarios with GAT (default, recommended)
    python scripts/phase5d_intervention.py

    # Specify architecture
    python scripts/phase5d_intervention.py --arch GAT
    python scripts/phase5d_intervention.py --arch GCN

    # Run single scenario
    python scripts/phase5d_intervention.py --scenario fuel_reduction
    python scripts/phase5d_intervention.py --scenario firebreak
    python scripts/phase5d_intervention.py --scenario ignition_suppression

PRE-CONDITIONS
--------------
    checkpoints/archive/phase5a_gat_best.pt
    data/processed/graph_data_enriched.pt
    data/features/feature_names.json
    data/features/target_transformer.pkl
    reports/tables/phase5b_gat_temperature.csv    (calibration T)

OUTPUTS
-------
    reports/tables/phase5d_intervention_summary.csv
    reports/tables/phase5d_{scenario}_effects.csv
    reports/predictions/phase5d_{scenario}_effects.npz
    reports/figures/  (generated by phase5d_make_figures.py)
"""

from __future__ import annotations
import os
os.environ["KMP_DUPLICATE_LIB_OK"] = "TRUE"

import sys
import json
import pickle
import argparse
import numpy as np
import pandas as pd
from pathlib import Path

import torch

PROJECT_ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(PROJECT_ROOT / "src"))

from wildfire_gnn.utils.config import load_yaml_config
from wildfire_gnn.models.gnn import build_model
from wildfire_gnn.models.intervention import (
    load_feature_names, get_feature_index,
    modify_feature_multiplicative, modify_feature_absolute,
    build_row_band_mask, build_region_mask,
    run_mc_inference, compute_intervention_effect,
    summarise_effect,
)

config   = load_yaml_config(PROJECT_ROOT / "configs" / "gnn_config.yaml")
p        = config["paths"]

GRAPH_PATH  = PROJECT_ROOT / p["graph_data"]
TRANS_PATH  = PROJECT_ROOT / p["target_transformer"]
FEAT_PATH   = PROJECT_ROOT / p["feature_names"]
CKPT_DIR    = PROJECT_ROOT / "checkpoints"
ARCHIVE_DIR = CKPT_DIR / "archive"
TBL_DIR     = PROJECT_ROOT / "reports" / "tables"
PRED_DIR    = PROJECT_ROOT / "reports" / "predictions"
TBL_DIR.mkdir(parents=True, exist_ok=True)
PRED_DIR.mkdir(parents=True, exist_ok=True)

N_MC = 30


def parse_args():
    p = argparse.ArgumentParser(description="Phase 5D — Intervention Analysis")
    p.add_argument("--arch", default="GAT",
                   choices=["GAT", "GCN", "GraphSAGE"])
    p.add_argument("--scenario", default="all",
                   choices=["all", "fuel_reduction",
                            "firebreak", "ignition_suppression"])
    p.add_argument("--n-mc", type=int, default=N_MC,
                   help="MC Dropout passes (default 30)")
    p.add_argument("--firebreak-row-min", type=int, default=5000,
                   help="Start row for firebreak strip (original raster coords)")
    p.add_argument("--firebreak-row-max", type=int, default=5100,
                   help="End row for firebreak strip (original raster coords)")
    return p.parse_args()


def load_model(arch: str) -> torch.nn.Module | None:
    ckpt_name = f"phase5a_{arch.lower()}_best.pt"
    ckpt_path = ARCHIVE_DIR / ckpt_name
    if not ckpt_path.exists():
        ckpt_path = CKPT_DIR / f"gnn_{arch.lower()}_best.pt"
    if not ckpt_path.exists():
        print(f"  ✗  Checkpoint not found for {arch}")
        return None
    ckpt  = torch.load(ckpt_path, map_location="cpu", weights_only=False)
    m_cfg = ckpt.get("config", config)["model"]
    model = build_model(
        architecture = arch,
        in_channels  = m_cfg["in_channels"],
        hidden       = m_cfg["hidden_channels"],
        num_layers   = m_cfg.get("num_layers", 4),
        heads        = m_cfg.get("heads", 8),
        dropout      = m_cfg.get("dropout", 0.3),
    )
    model.load_state_dict(ckpt["model_state"])
    print(f"  ✓  {arch} loaded from {ckpt_path.name}")
    return model


def load_temperature(arch: str) -> float:
    """Load calibrated temperature T from Phase 5B."""
    temp_path = TBL_DIR / f"phase5b_{arch.lower()}_temperature.csv"
    if temp_path.exists():
        df = pd.read_csv(temp_path)
        T  = float(df["T"].iloc[0])
        print(f"  ✓  Temperature T={T:.4f} loaded from {temp_path.name}")
        return T
    else:
        print(f"  ⚠  Temperature CSV not found — using T=1.0 (uncalibrated)")
        print(f"     Run Phase 5B first: python scripts/phase5b_calibrate.py --arch {arch}")
        return 1.0


def get_baseline_predictions(
    model, graph, transformer, test_mask, n_mc, temperature
) -> dict:
    """Run MC inference on ORIGINAL graph to get baseline predictions."""
    print(f"\n  Getting baseline predictions (original graph, {n_mc} MC passes)...")
    mc = run_mc_inference(
        model       = model,
        graph_x     = graph.x,
        edge_index  = graph.edge_index,
        test_mask   = test_mask,
        n_samples   = n_mc,
        temperature = temperature,
    )
    y_orig_bp = transformer.inverse_transform(
        mc["mean_pred"].reshape(-1,1)
    ).ravel()

    # Verify R² matches confirmed result
    y_true_bp = graph.y_raw[test_mask].numpy().ravel()
    ss_res = np.sum((y_true_bp - y_orig_bp)**2)
    ss_tot = np.sum((y_true_bp - y_true_bp.mean())**2)
    r2     = float(1 - ss_res/ss_tot)
    print(f"  ✓  Baseline R²={r2:.4f}  (should be ~0.766 for GAT)")
    return mc, y_true_bp


def run_fuel_reduction(
    model, graph, transformer, test_mask,
    feature_names, n_mc, temperature,
    mc_orig,
) -> tuple[dict, dict]:
    """
    Scenario 1: Reduce CFL by 30% across all test nodes.

    Physical meaning: Systematic fuel treatment programme reducing
    Crown Fire Likelihood by 30% landscape-wide. This represents
    the effect of prescribed burning or mechanical fuel removal.

    Feature modified: CFL (Crown Fire Likelihood)
    Delta: -30% (multiplicative)
    Region: all nodes (landscape-wide)
    """
    print("\n  ── Scenario 1: Fuel Reduction 30% ──")
    print("  Reducing CFL by 30% across all nodes...")

    cfl_idx = get_feature_index("CFL", feature_names)
    print(f"  CFL feature index: {cfl_idx}")

    orig_cfl_mean = float(graph.x[:, cfl_idx].mean())
    print(f"  Original CFL mean: {orig_cfl_mean:.4f}")

    x_modified = modify_feature_multiplicative(
        graph.x, cfl_idx, delta_fraction=-0.30
    )
    new_cfl_mean = float(x_modified[:, cfl_idx].mean())
    print(f"  Modified CFL mean: {new_cfl_mean:.4f}  "
          f"({100*(new_cfl_mean/orig_cfl_mean - 1):.1f}%)")

    print(f"  Running {n_mc} MC passes on modified graph...")
    mc_new = run_mc_inference(
        model, x_modified, graph.edge_index,
        test_mask, n_mc, temperature
    )

    effect = compute_intervention_effect(mc_orig, mc_new, transformer, temperature)
    summary = summarise_effect(
        effect, "Fuel Reduction 30%",
        int(test_mask.sum()),
        intervention_mask=None,  # all test nodes treated
        verbose=True,
    )
    return effect, summary


def run_firebreak(
    model, graph, transformer, test_mask,
    feature_names, n_mc, temperature,
    mc_orig, row_min, row_max,
) -> tuple[dict, dict]:
    """
    Scenario 2: Add a firebreak by setting CFL=0 in a horizontal strip.

    Physical meaning: Physical barrier (road, cleared strip, water body)
    that prevents crown fire propagation. CFL=0 means no crown fire
    likelihood — fire cannot spread through the canopy in this area.

    Feature modified: CFL
    Delta: set to 0 (absolute)
    Region: raster rows [row_min, row_max] — a horizontal landscape strip
    """
    print(f"\n  ── Scenario 2: Firebreak Strip (rows {row_min}–{row_max}) ──")

    cfl_idx = get_feature_index("CFL", feature_names)

    # Build spatial mask for the firebreak strip
    strip_mask = build_row_band_mask(graph.pos, row_min, row_max)
    n_strip    = int(strip_mask.sum())
    print(f"  Strip covers {n_strip:,} nodes"
          f"  ({100*n_strip/graph.num_nodes:.1f}% of full graph)")

    # Modify: set CFL=0 in strip
    x_modified = modify_feature_absolute(
        graph.x, cfl_idx, new_value=0.0,
        node_mask=strip_mask,
    )

    # Which test nodes are in the firebreak strip?
    test_in_strip = strip_mask[test_mask]
    n_test_in_strip = int(test_in_strip.sum())
    print(f"  Test nodes in strip: {n_test_in_strip:,}"
          f"  ({100*n_test_in_strip/int(test_mask.sum()):.1f}% of test)")

    print(f"  Running {n_mc} MC passes on modified graph...")
    mc_new = run_mc_inference(
        model, x_modified, graph.edge_index,
        test_mask, n_mc, temperature
    )

    effect = compute_intervention_effect(mc_orig, mc_new, transformer, temperature)

    # Evaluate effect on ALL test nodes — firebreak affects beyond strip
    # through message-passing propagation
    summary = summarise_effect(
        effect, f"Firebreak Strip (rows {row_min}-{row_max})",
        int(test_mask.sum()),
        intervention_mask=None,  # report effect across all test nodes
        verbose=True,
    )

    # Also compute effect specifically in/near the strip
    if n_test_in_strip > 0:
        strip_effect_mean = float(effect["delta_bp"][test_in_strip.numpy()].mean())
        print(f"\n  Effect in strip region: mean Δ BP = {strip_effect_mean:+.5f}")
        print(f"  Effect outside strip (propagated): "
              f"mean Δ BP = {effect['delta_bp'][~test_in_strip.numpy()].mean():+.5f}")

    summary["n_strip_nodes_in_test"] = n_test_in_strip
    summary["mean_delta_in_strip"]   = float(
        effect["delta_bp"][test_in_strip.numpy()].mean()
    ) if n_test_in_strip > 0 else 0.0

    return effect, summary


def run_ignition_suppression(
    model, graph, transformer, test_mask,
    feature_names, n_mc, temperature,
    mc_orig,
) -> tuple[dict, dict]:
    """
    Scenario 3: Reduce Ignition_Prob by 50% across all nodes.

    Physical meaning: Improved fire detection systems, suppression
    resources pre-positioned in high-risk areas, or behaviour change
    programs reducing human-caused ignitions. Models a 50% reduction
    in fire ignition probability.

    Feature modified: Ignition_Prob
    Delta: -50% (multiplicative)
    Region: all nodes (landscape-wide)
    """
    print("\n  ── Scenario 3: Ignition Suppression 50% ──")
    print("  Reducing Ignition_Prob by 50% across all nodes...")

    ign_idx = get_feature_index("Ignition_Prob", feature_names)
    print(f"  Ignition_Prob feature index: {ign_idx}")

    orig_ign_mean = float(graph.x[:, ign_idx].mean())
    print(f"  Original Ignition_Prob mean: {orig_ign_mean:.4f}")

    x_modified = modify_feature_multiplicative(
        graph.x, ign_idx, delta_fraction=-0.50
    )
    new_ign_mean = float(x_modified[:, ign_idx].mean())
    print(f"  Modified Ignition_Prob mean: {new_ign_mean:.4f}  "
          f"({100*(new_ign_mean/orig_ign_mean - 1):.1f}%)")

    print(f"  Running {n_mc} MC passes on modified graph...")
    mc_new = run_mc_inference(
        model, x_modified, graph.edge_index,
        test_mask, n_mc, temperature
    )

    effect = compute_intervention_effect(mc_orig, mc_new, transformer, temperature)
    summary = summarise_effect(
        effect, "Ignition Suppression 50%",
        int(test_mask.sum()),
        intervention_mask=None,
        verbose=True,
    )
    return effect, summary


def save_effects(arch: str, scenario: str, effect: dict) -> None:
    """Save full per-node effect arrays as NPZ."""
    out = PRED_DIR / f"phase5d_{scenario}_{arch.lower()}_effects.npz"
    np.savez_compressed(
        out,
        delta_bp         = effect["delta_bp"].astype(np.float32),
        delta_std_bp     = effect["delta_std_bp"].astype(np.float32),
        delta_bp_lo_90   = effect["delta_bp_lo_90"].astype(np.float32),
        delta_bp_hi_90   = effect["delta_bp_hi_90"].astype(np.float32),
        y_orig_bp        = effect["y_orig_bp"].astype(np.float32),
        y_new_bp         = effect["y_new_bp"].astype(np.float32),
        significant_mask = effect["significant_mask"],
        delta_samples_bp = effect["delta_samples_bp"].astype(np.float32),
    )
    size_mb = out.stat().st_size / 1024**2
    print(f"  ✓  Saved: {out.name}  ({size_mb:.1f} MB)")


def main():
    args = parse_args()
    arch = args.arch

    print("\n" + "="*65)
    print(f"  Phase 5D — Counterfactual Intervention Analysis  [{arch}]")
    print("="*65 + "\n")

    # Load everything
    print("  Loading assets...")
    graph        = torch.load(GRAPH_PATH, map_location="cpu", weights_only=False)
    with open(TRANS_PATH, "rb") as f:
        transformer = pickle.load(f)
    feature_names = load_feature_names(FEAT_PATH)
    model         = load_model(arch)
    temperature   = load_temperature(arch)

    if model is None:
        sys.exit(1)

    print(f"\n  Graph: {graph.num_nodes:,} nodes  "
          f"Test: {int(graph.test_mask.sum()):,}")
    print(f"  Features: {graph.num_node_features}")
    print(f"  Temperature T: {temperature:.4f} (Phase 5B)")

    # Verify CFL and Ignition_Prob indices
    cfl_idx = get_feature_index("CFL", feature_names)
    ign_idx = get_feature_index("Ignition_Prob", feature_names)
    print(f"\n  Feature indices:")
    print(f"    CFL           : {cfl_idx}  "
          f"(mean={float(graph.x[:,cfl_idx].mean()):.4f})")
    print(f"    Ignition_Prob : {ign_idx}  "
          f"(mean={float(graph.x[:,ign_idx].mean()):.4f})")

    # Baseline predictions (original graph)
    mc_orig, y_true_bp = get_baseline_predictions(
        model, graph, transformer, graph.test_mask,
        args.n_mc, temperature
    )

    # Run scenarios
    all_summaries = []
    scenarios     = args.scenario

    if scenarios in ("all", "fuel_reduction"):
        effect, summary = run_fuel_reduction(
            model, graph, transformer, graph.test_mask,
            feature_names, args.n_mc, temperature, mc_orig
        )
        save_effects(arch, "fuel_reduction_30pct", effect)
        all_summaries.append(summary)

    if scenarios in ("all", "firebreak"):
        effect, summary = run_firebreak(
            model, graph, transformer, graph.test_mask,
            feature_names, args.n_mc, temperature, mc_orig,
            row_min=args.firebreak_row_min,
            row_max=args.firebreak_row_max,
        )
        save_effects(arch, "firebreak", effect)
        all_summaries.append(summary)

    if scenarios in ("all", "ignition_suppression"):
        effect, summary = run_ignition_suppression(
            model, graph, transformer, graph.test_mask,
            feature_names, args.n_mc, temperature, mc_orig
        )
        save_effects(arch, "ignition_suppression_50pct", effect)
        all_summaries.append(summary)

    # Save summary table
    if all_summaries:
        df = pd.DataFrame(all_summaries)
        df["arch"] = arch
        out_csv = TBL_DIR / "phase5d_intervention_summary.csv"
        df.to_csv(out_csv, index=False)
        print(f"\n  ✓  Summary saved: {out_csv.name}")

    # Print final comparison
    print(f"\n{'='*65}")
    print(f"  INTERVENTION SUMMARY — {arch}")
    print(f"{'='*65}")
    print(f"  {'Scenario':<30} {'Mean Δ BP':>10} {'Pct reduced':>12} "
          f"{'Significant':>12}")
    print(f"  {'-'*65}")
    for s in all_summaries:
        print(f"  {s['scenario']:<30} {s['mean_delta_bp']:>+10.5f} "
              f"{s['pct_reduced']:>11.1f}% "
              f"{s['pct_significant']:>11.1f}%")
    print(f"{'='*65}")
    print(f"\n  Run figures: python scripts/phase5d_make_figures.py --arch {arch}")
    print()


if __name__ == "__main__":
    main()